#ejercicio de agregar y quitar primary keys
CREATE DATABASE grupos;
USE grupos;


CREATE TABLE ZONAS(
ID INT NOT NULL,
DIR_COD INT NOT NULL,
DIR VARCHAR (20),
NOMBRE VARCHAR(20)
);

DESC ZONAS;#DESCRIBE LA BASE DE DATOS 

ALTER TABLE ZONAS

ADD PRIMARY KEY (ID);
DESC ZONAS;

CREATE TABLE GRUPO_1(
ID INT NOT NULL,
DIR_COD INT NOT NULL,
NOMBRE VARCHAR(20),
PRIMARY KEY (ID)
);
DESC GRUPO_1;
#ELIMINAR EL ATRIBUTO DE CLAVE PRIMARIA 
ALTER TABLE ZONAS 
DROP PRIMARY KEY ;
DESC ZONAS;



