#ejercicio 1
CREATE DATABASE VET;
USE VET;
# crear una tabla de mascotas , campos : id , nombre , id_dueno , sevicio
CREATE TABLE MASCOTAS (
ID INT NOT NULL,
NOMBRE VARCHAR(20),
ID_DUENO  INT NOT NULL,
SERVICIO VARCHAR(20)
);

#crear tablas personas , campos : id , nombre, apellido , id_dueno , cod_zip, tlf 
CREATE TABLE PERSONAS(
ID INT NOT NULL,
NOMBRE VARCHAR(20),
APELLIDO VARCHAR (20),
ID_DUENO INT NOT NULL,
COD_ZIP INT NOT NULL,
TLF INT 
);

#crear tabla direcciones , campos : zip , nombre_zona, ruta
CREATE TABLE DIRECCIONES (
ZIP INT NOT NULL ,
NOMBRE_ZONA VARCHAR(8),
RUTA VARCHAR(20)
);

DESC MASCOTAS ;
DESC PERSONA;
DESC DIRECCIONES ;

#EJERCICIO 1
#AGREGAR PK AL CAMPO ID EN MASCOTAS
ALTER TABLE MASCOTAS
ADD PRIMARY KEY (ID);

DESC MASCOTAS;

#AGREGAR PK AL CAMPO ID EN PERSONAS
ALTER TABLE PERSONA
ADD PRIMARY KEY (ID);

DESC PERSONA;

#AGREGAR PK AL CAMPO ZIP EN DIRECCIONES
ALTER TABLE DIRECCIONES
ADD PRIMARY KEY (ZIP);

DESC DIRECCIONES;

#AGREGAR FK EN EL CAMPO ID_DUENO EN MACOTAS -> PERSONA
DESC MASCOTAS;
ALTER TABLE MASCOTAS
ADD CONSTRAINT FK_DUENOS_ID
FOREIGN KEY (ID_DUENO) REFERENCES PERSONA(ID);

#AGREGAR FK EN EL CAMPO ZIPCODE EN PERONSAS -> DIRECCIONES 
DESC PERSONA ;
ALTER TABLE PERSONA
ADD CONSTRAINT FK_ZIP_DIR
FOREIGN KEY (COD_ZIP) REFERENCES DIRECCIONES (ZIP);
DESC PERSONA;

#AGREGAR COLUMNA  A EMAIL EN PERSONAS
DESC PERSONA ;
ALTER TABLE PERSONNA
ADD COLUMN EMAIL VARCHAR(20);

DESC PERSONA;
# AGREGAR UNIQUE CONSTRAINT A EMAIL EN PERSONAS 
DESC PERSONA;
ALTER TABLE PERSONA
ADD CONSTRAINT U_EMAIL
UNIQUE (EMAIL);
DESC PERSONA;
#CAMBIAR EL NOMBRE AL CAMPO PERSONSA ->PRIMER PERSONA
DESC MASCOTAS;
ALTER TABLE MASCOTAS 
RENAME COLUMN NOMBRE TO PRIMER_NOMBRE;
DESC MASCOTAS;
# CAMBIAR EL TIPO DE DATO AL CAMPO RUTA EN DIRECCIONES -> CHAR (12)
DESC DIRECCIONES;
ALTER TABLE DIRECCIONES
MODIFY RUTA CHAR(12);
DESC DIRECCIONES;







